#!/usr/bin/bash

# i got this is from valve lmao
ROOT=$(cd "${0%/*}" && echo $PWD)
LIBROOT="$(realpath ${ROOT}/../lib/i386-lemonos)"

CCFLAGS="-fno-stack-protector -fPIE -mno-avx -mhard-float -static -m32 -fno-builtin -fno-builtin-function -fomit-frame-pointer -falign-functions=16 -nostdlib -nostartfiles -ffreestanding -nostdinc -funsigned-char -I${LIBROOT}/include -I${LIBROOT}/inked_include"
LINK="1"

ARGS=( )

OUTPUT="a.out"
while test $# -gt 0; do
	case "$1" in
		-o)
			OUTPUT="$2"
			shift
			;;
		*)
			ARGS+=("$1")
			;;
	esac
	shift
done

if [[ "${ARGS[*]}" == *"-c"* ]]; then
	LINK="0"
fi

if [[ "${ARGS[@]}" == "" ]]; then
	gcc $CCFLAGS $ARGS
	exit
fi

TMP="$(mktemp)"
rm $TMP
TMP="$TMP.o"

gcc $CCFLAGS ${ARGS[@]} "$@" -c -o $TMP

if [[ ! -f $TMP ]]; then
	exit
fi

if [[ "$LINK" == "1" ]]; then
	i386-ld-lemonos $TMP -o $OUTPUT
else
	mv $TMP $OUTPUT
fi
rm -f $TMP
